import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

export async function generatePhysicsTest() {
    if (!vscode.workspace.workspaceFolders) {
        vscode.window.showErrorMessage('No workspace folder open.');
        return;
    }

    const workspaceRoot = vscode.workspace.workspaceFolders[0].uri.fsPath;
    const subsystemName = await vscode.window.showInputBox({
        prompt: 'Enter the Subsystem name (e.g. Climber)',
        placeHolder: 'Climber'
    });

    if (!subsystemName) return;

    const className = `MARS${subsystemName}`;
    const testClassName = `${className}Test`;
    const targetPath = path.join(workspaceRoot, 'src', 'test', 'java', 'frc', 'robot', 'subsystems', `${testClassName}.java`);

    if (fs.existsSync(targetPath)) {
        const overwrite = await vscode.window.showWarningMessage(`Test file ${testClassName} already exists. Overwrite?`, 'Yes', 'No');
        if (overwrite !== 'Yes') return;
    }

    const template = `package frc.robot.subsystems;

import static org.junit.jupiter.api.Assertions.*;

import com.marslib.testing.MARSTestHarness;
import edu.wpi.first.hal.HAL;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Physics-Integration test for ${className}.
 * Generated by MARSLib VS Code Extension.
 */
public class ${testClassName} {
  private ${className} subsystem;

  @BeforeEach
  public void setUp() {
    MARSTestHarness.reset();
    
    // Initialize subsystem with Mock/Sim IO
    // subsystem = new ${className}(...);
  }

  @AfterEach
  public void tearDown() {
    MARSTestHarness.cleanup();
  }

  @Test
  public void testInitialization() {
    assertNotNull(subsystem, "${className} should be initialized");
  }

  @Test
  public void testBasicSafety() {
    // Verify that the subsystem doesn't move without voltage
    // assertEquals(0, subsystem.getPosition());
  }
}
`;

    const dir = path.dirname(targetPath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(targetPath, template);
    const doc = await vscode.workspace.openTextDocument(targetPath);
    await vscode.window.showTextDocument(doc);
    vscode.window.showInformationMessage(`Physics test for ${className} generated successfully.`);
}
